# Generated by Django 4.2.4 on 2023-09-28 12:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', upload_to=users.models.CustomUser.image_upload_to),
        ),
    ]
