# Generated by Django 4.2.5 on 2023-11-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('cliente', 'cliente'), ('Auxiliar', 'Auxiliar'), ('Administrativo', 'Administrativo'), ('Farmaceutico', 'Farmaceutico'), ('Medico', 'Medico')], default='Empleado', max_length=100),
        ),
    ]
