# Generated by Django 4.2.5 on 2023-11-02 12:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, verbose_name='Accion Farmatologica')),
                ('article_slug', models.SlugField(unique=True, verbose_name='Codigo de Barra')),
                ('principio_activo', models.CharField(max_length=17, verbose_name='Droga')),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Presentacion')),
                ('tipo_Producto', models.CharField(choices=[('venta libre', 'Venta Libre'), ('bajo receta', 'Bajo Receta'), ('bajo receta duplicada', 'Bajo receta duplicado-Lista IV')], max_length=45)),
                ('notes', ckeditor.fields.RichTextField(blank=True, default='')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha publicada')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha modificada')),
                ('image', models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=main.models.Article.image_upload_to, verbose_name='Imagen')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tipo de Producto')),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, verbose_name='subtitulo')),
                ('slug', models.SlugField(unique=True, verbose_name='Etiqueta')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Publicada')),
                ('image', models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=main.models.ArticleSeries.image_upload_to, verbose_name='Imagen')),
            ],
            options={
                'verbose_name_plural': 'Tipos de producto',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id_Direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('número', models.IntegerField(verbose_name='Numero')),
                ('piso', models.IntegerField(null=True, verbose_name='N° Piso')),
                ('departamento', models.CharField(max_length=50, null=True, verbose_name='Departamento')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('código_Postal', models.IntegerField(null=True, verbose_name='Codigo Postal')),
            ],
        ),
        migrations.CreateModel(
            name='telefono',
            fields=[
                ('id_Telefonos', models.AutoField(primary_key=True, serialize=False)),
                ('numero_Telefono', models.IntegerField(null=True, verbose_name='Numero')),
                ('numero_Opcional', models.IntegerField(null=True, verbose_name='Numero opcional')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=17, verbose_name='Nombre')),
                ('r_Social', models.CharField(max_length=50, verbose_name='Razon Social')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo Electronico')),
                ('fto_proveedor', models.ImageField(blank=True, null=True, upload_to='static/usuarios', verbose_name='Foto de Proveedor')),
                ('id_Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.direccion')),
                ('id_Telefonos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.telefono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'unique_together': {('nombre', 'r_Social', 'correo')},
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_Paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=17, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='Dni')),
                ('nacimiento', models.DateField(verbose_name='Nacimiento')),
                ('fto_Paciente', models.ImageField(blank=True, null=True, upload_to='static/usuarios', verbose_name='Foto de Perfil del Paciente')),
                ('id_Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.direccion')),
                ('id_Telefonos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.telefono')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'unique_together': {('nombre', 'apellido', 'dni')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_Movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('0', 'Ingreso'), ('1', 'Egreso')], max_length=1, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha_Caducidad', models.DateField(verbose_name='Fecha de caducidad')),
                ('recetas', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Recetas')),
                ('duplicado', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Duplicado')),
                ('id_Paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.paciente')),
                ('id_Proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.proveedor')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_Laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fto_Laboratorio', models.ImageField(blank=True, null=True, upload_to='static/usuarios', verbose_name='Imagen laboratorio')),
                ('id_Direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.direccion')),
                ('id_Telefonos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.telefono')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'unique_together': {('nombre', 'id_Direccion', 'id_Telefonos')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='id_Laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.laboratorio'),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.articleseries', verbose_name='Series'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_Empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=17, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='Dni')),
                ('trabajo', models.CharField(choices=[('Auxiliar', 'Auxiliar'), ('Administrativo', 'Administrativo'), ('Farmaceutico', 'Farmaceutico'), ('Medico', 'Medico')], max_length=20, verbose_name='Puesto')),
                ('nacimiento', models.DateField(verbose_name='Nacimiento')),
                ('fto_Empleado', models.ImageField(blank=True, null=True, upload_to='static/usuarios', verbose_name='Foto de Perfil')),
                ('id_Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.direccion')),
                ('id_Telefonos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.telefono')),
                ('id_usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'unique_together': {('nombre', 'apellido', 'dni')},
            },
        ),
    ]
